### PR TITLE
Update operator workflow for non-Jib build

### PR DESCRIPTION
**Pull request by ASzc**
This is related to https://github.com/keycloak/keycloak/pull/19642

Not really sure if this will work or not. The docker build plugin doesn't offer the same stuff as Jib does

### CODE REVIEW

**Comment by ASzc** [comment]
Seems to have worked with the improved local coordinate: https://github.com/keycloak-rel-testing/keycloak-rel/actions/runs/4745879861/jobs/8429965548

I will update this PR

**Comment by ASzc** [comment]
I read that. I don't know if I'm misunderstanding it, but it seems to say the sync from `keycloak-rel-testing/keycloak-rel` to `keycloak-rel/keycloak-rel` is not something I, as a contributor, should do. The maintainer does a PR after keycloak-rel-testing is updated by my PR

**Comment by stianst** [comment]
It's a little bit awkward, but you need to send the changes to a branch in keycloak-rel-testing so the change can be tested. Then once it passes the nightly and release jobs a PR can be opened from the branch in keycloak-rel-testing to keycloak-rel.

**Comment by vmuzikar** [comment]
@stianst Thanks for clarifying!

Based on that I created https://github.com/keycloak-rel/keycloak-rel/pull/95

@ASzc Can you please review? And perhaps we can close this one?

**Pull request closed without merging**
